# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TACKtical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for TACKtical
  pod 'Firebase/Storage'
  platform :ios, '10.0'

  target 'TACKticalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TACKticalUITests' do
    # Pods for testing
  end

end