# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TACKtical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tacktical
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'FBSDKCoreKit'
 	pod 'FBSDKLoginKit'
end
